### ISSUE TITLE
rename.sh leaves a lot of residue files on MacOS

### ISSUE THREAD

**Issue by facundomedica** [cosmosregistry/example#25]
I suppose this is something specific to MacOS. For every file I get 2 files with the same name suffixed with "-e" or "-e-e"

**Comment by facundomedica** [comment]
> -i '' works with OS X's sed but not GNU sed. -i works with GNU sed, recent versions of NetBSD, OpenBSD sed, but not OS X's sed. -i -e works with both but in the case of FreeBSD sed makes a backup of the original file with -e appended to the file name (and you need to pass no more than one expression to sed).

https://unix.stackexchange.com/questions/13711/differences-between-sed-on-mac-osx-and-other-standard-sed

**Comment by facundomedica** [comment]
Adding an empty string after -i works. Not sure if that breaks something on other platforms tho:

```
... -i '' -e ...
```

**Comment by julienrbrt** [comment]
Would it be overkilled to use a linux docker image to run the script?
I believe we do that in the sdk for proto-builder for instance.

**Comment by julienrbrt** [comment]
Solved in https://github.com/cosmosregistry/example/commit/6324c4104bd8ed915812e1fb69d933c4549250ab
