### ISSUE TITLE
`rename.sh` doesn't accept names with '-' or multi slashes

### ISSUE THREAD

**Issue by srdtrk** [cosmosregistry/example#44]
## Description
Rename script doesn't accept names with `-` or names with multi slashes such as `srdtrk/long/name`

### Including '-'
Many production modules include '-' in their name such as `ibc-go` or `packet-forward-middleware`. Doing this yields
```
Generating protobuf files...
Generating gogo proto code
srdtrk/dashed-name/module/v1/module.proto:3:22:syntax error: unexpected '-', expecting ';'
srdtrk/dashed-name/v1/query.proto:2:22:syntax error: unexpected '-', expecting ';'
srdtrk/dashed-name/v1/tx.proto:2:22:syntax error: unexpected '-', expecting ';'
srdtrk/dashed-name/v1/types.proto:2:22:syntax error: unexpected '-', expecting ';'
make: *** [Makefile:31: proto-gen] Error 100
```

### Multi Slashes
Multi slashes are also very common. Giving a such a name yields:
```
Generating protobuf files...
Generating gogo proto code
Generating pulsar proto code
```
And the resulting sdk module doesn't work. (This doesn't even give an error message)

**Comment by julienrbrt** [comment]
By long name, do you mean names with multi slashes?
I think we are going to deprecate the rename script for https://go.dev/blog/gonew instead.

**Comment by srdtrk** [comment]
Yes, I mean multi slashes

**Comment by julienrbrt** [comment]
Added instructions and disclaimer (https://github.com/cosmosregistry/example/commit/754905aed278b9f01edda15b4b16a5f7ef1499f2), if someone is willing to fix the script to support this use case, feel free to send a PR.
For now, I am closing this as won't do.
